<a href="https://colab.research.google.com/github/shemi024/regression-correlation/blob/main/trelloMLcar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
data=pd.read_csv('/content/drive/MyDrive/car_crashes.csv')

In [ ]:
data.shape

(51, 8)

In [ ]:
data.dtypes

total             float64
speeding          float64
alcohol           float64
not_distracted    float64
no_previous       float64
ins_premium       float64
ins_losses        float64
abbrev             object
dtype: object

In [ ]:
data.isna().sum()

total             0
speeding          0
alcohol           0
not_distracted    0
no_previous       0
ins_premium       0
ins_losses        0
abbrev            0
dtype: int64

In [ ]:
data.head()

   total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
0   18.8     7.332    5.640  ...       784.55      145.08      AL
1   18.1     7.421    4.525  ...      1053.48      133.93      AK
2   18.6     6.510    5.208  ...       899.47      110.35      AZ
3   22.4     4.032    5.824  ...       827.34      142.39      AR
4   12.0     4.200    3.360  ...       878.41      165.63      CA

[5 rows x 8 columns]

In [ ]:
data.abbrev.nunique()

51

In [ ]:
data.drop('abbrev',axis=1,inplace=True)

In [ ]:
data=pd.get_dummies(data)

In [ ]:
data

    total  speeding  alcohol  ...  no_previous  ins_premium  ins_losses
0    18.8     7.332    5.640  ...       15.040       784.55      145.08
1    18.1     7.421    4.525  ...       17.014      1053.48      133.93
2    18.6     6.510    5.208  ...       17.856       899.47      110.35
3    22.4     4.032    5.824  ...       21.280       827.34      142.39
4    12.0     4.200    3.360  ...       10.680       878.41      165.63
5    13.6     5.032    3.808  ...       12.920       835.50      139.91
6    10.8     4.968    3.888  ...        8.856      1068.73      167.02
7    16.2     6.156    4.860  ...       16.038      1137.87      151.48
8     5.9     2.006    1.593  ...        5.900      1273.89      136.05
9    17.9     3.759    5.191  ...       16.826      1160.13      144.18
10   15.6     2.964    3.900  ...       14.508       913.15      142.80
11   17.5     9.450    7.175  ...       15.225       861.18      120.92
12   15.3     5.508    4.437  ...       14.994       641.96       82.75
13   12.8     4.608    4.352  ...       12.288       803.11      139.15
14   14.5     3.625    4.205  ...       13.775       710.46      108.92
15   15.7     2.669    3.925  ...       13.659       649.06      114.47
16   17.8     4.806    4.272  ...       15.130       780.45      133.80
17   21.4     4.066    4.922  ...       16.264       872.51      137.13
18   20.5     7.175    6.765  ...       20.090      1281.55      194.78
19   15.1     5.738    4.530  ...       12.684       661.88       96.57
20   12.5     4.250    4.000  ...       12.375      1048.78      192.70
21    8.2     1.886    2.870  ...        6.560      1011.14      135.63
22   14.1     3.384    3.948  ...       10.857      1110.61      152.26
23    9.6     2.208    2.784  ...        8.448       777.18      133.35
24   17.6     2.640    5.456  ...       17.600       896.07      155.77
25   16.1     6.923    5.474  ...       13.524       790.32      144.45
26   21.4     8.346    9.416  ...       18.190       816.21       85.15
27   14.9     1.937    5.215  ...       13.410       732.28      114.82
28   14.7     5.439    4.704  ...       14.553      1029.87      138.71
29   11.6     4.060    3.480  ...        9.628       746.54      120.21
30   11.2     1.792    3.136  ...        8.736      1301.52      159.85
31   18.4     3.496    4.968  ...       18.032       869.85      120.75
32   12.3     3.936    3.567  ...        9.840      1234.31      150.01
33   16.8     6.552    5.208  ...       13.608       708.24      127.82
34   23.9     5.497   10.038  ...       20.554       688.75      109.72
35   14.1     3.948    4.794  ...       11.562       697.73      133.52
36   19.9     6.368    5.771  ...       18.706       881.51      178.86
37   12.8     4.224    3.328  ...       11.520       804.71      104.61
38   18.2     9.100    5.642  ...       16.016       905.99      153.86
39   11.1     3.774    4.218  ...        8.769      1148.99      148.58
40   23.9     9.082    9.799  ...       19.359       858.97      116.29
41   19.4     6.014    6.402  ...       16.684       669.31       96.87
42   19.5     4.095    5.655  ...       15.795       767.91      155.57
43   19.4     7.760    7.372  ...       16.878      1004.75      156.83
44   11.3     4.859    1.808  ...       10.848       809.38      109.48
45   13.6     4.080    4.080  ...       12.920       716.20      109.61
46   12.7     2.413    3.429  ...       11.176       768.95      153.72
47   10.6     4.452    3.498  ...        9.116       890.03      111.62
48   23.8     8.092    6.664  ...       20.706       992.61      152.56
49   13.8     4.968    4.554  ...       11.592       670.31      106.62
50   17.4     7.308    5.568  ...       15.660       791.14      122.04

[51 rows x 7 columns]

In [ ]:
x=data.drop(['total'],axis=1)
y=data['total']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test =train_test_split(x,y, random_state=42, test_size=0.2)

In [ ]:
x_train.shape

(40, 6)

In [ ]:
from sklearn.linear_model import LinearRegression
logis_model = LinearRegression()
model=logis_model.fit(x_train, y_train)
y_pred = model.predict(x_test)

In [ ]:
# y_pred= model.predict(x_test)  
# x_pred= model.predict(x_train)

In [ ]:

from sklearn.metrics import mean_squared_error, r2_score
mean_squared_error(y_test, y_pred)
r2_score(y_test, y_pred)

0.8791208489722766

In [ ]:
#KNN
from sklearn import neighbors
from sklearn.metrics import mean_squared_error 
from math import sqrt

model = neighbors.KNeighborsRegressor(n_neighbors = 5)
model.fit(x_train, y_train)  #fit the model    
predicted = model.predict(x_test)
error = mean_squared_error(y_test,predicted)
print(error)

21.577599999999993